### ISSUE TITLE
Cascades

### ISSUE THREAD

**Issue by lejabque** [NuMellow/roadHog#1]
Hey, have you got cascades from this project?
I'll be very grateful

**Comment by berkaygunler** [comment]
Hey, can you share the cascade files?

**Comment by NuMellow** [comment]
Hey, Sorry for some reason I did not get any notification for the issue. I'm not sure if it's still relevant to you but yes I can upload the cascade files. (Hope I still have them).

**Comment by NuMellow** [comment]
Added the files. 

Note: When I made these cascades I trained them to detect a particular image so while it may still work with different stop signs for instance, it will perform best with the ones it trained on. In hindsight it would be better to train with different types of stop signs.
